// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-y58OnYcVFs9BW4SF9jbdPeEkmpr9HM',
    appId: '1:996643637532:web:5cb09d12a96a20881292d9',
    messagingSenderId: '996643637532',
    projectId: 'cd-automation-b92ca',
    authDomain: 'cd-automation-b92ca.firebaseapp.com',
    storageBucket: 'cd-automation-b92ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzL4RajABJqBUXBxfMXO33mzPbqY4I3Y',
    appId: '1:996643637532:android:639e399a0bd36dc01292d9',
    messagingSenderId: '996643637532',
    projectId: 'cd-automation-b92ca',
    storageBucket: 'cd-automation-b92ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfWYk0pgXBgAlC1eNxbNhBP9zF0MoVIU8',
    appId: '1:996643637532:ios:0220ec9e43d43e901292d9',
    messagingSenderId: '996643637532',
    projectId: 'cd-automation-b92ca',
    storageBucket: 'cd-automation-b92ca.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfWYk0pgXBgAlC1eNxbNhBP9zF0MoVIU8',
    appId: '1:996643637532:ios:0220ec9e43d43e901292d9',
    messagingSenderId: '996643637532',
    projectId: 'cd-automation-b92ca',
    storageBucket: 'cd-automation-b92ca.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_-y58OnYcVFs9BW4SF9jbdPeEkmpr9HM',
    appId: '1:996643637532:web:e352fc22274be6cf1292d9',
    messagingSenderId: '996643637532',
    projectId: 'cd-automation-b92ca',
    authDomain: 'cd-automation-b92ca.firebaseapp.com',
    storageBucket: 'cd-automation-b92ca.firebasestorage.app',
  );

}